services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-api:latest
    container_name: app
    volumes:
      - ./:/var/www
    networks:
      - app_network
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: app_nginx
    ports:
      - "8085:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: