openapi: 3.0.1
info:
  title: 77Sol Project API
  description: API para o projeto 77Sol
  version: "1.0.0"
  
tags: 
  - name: Login
  - name: Customers
  - name: Projects
  - name: Equipments
  - name: Installation Types

servers:
  - url: "http://localhost:8085"

paths:
  /api/login:
    post:
      summary: Login
      tags:
        - Login
      description: Login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login efetuado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Credenciais inválidas.

  /api/customers:
    get:
      summary: Get All Customers
      tags:
        - Customers
      description: Retorna uma lista de clientes com base nos parâmetros de consulta.
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: email
          in: query
          schema:
            type: string
        - name: phone
          in: query
          schema:
            type: string
        - name: document
          in: query
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de clientes retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                    document:
                      type: string
    post:
      summary: New Customer
      tags:
        - Customers
      description: Cria um novo cliente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                document:
                  type: string
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Cliente criado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  document:
                    type: string
        "400":
          description: Documento inválido
        "422":
          description: Parâmetros inválidos

  /api/customers/{id}:
    get:
      summary: Get Customer By ID
      tags:
        - Customers
      description: Retorna um cliente específico pelo ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Cliente encontrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  document:
                    type: string
        "422":
          description: Parâmetros inválidos
    put:
      summary: Update Customer
      tags:
        - Customers
      description: Atualiza informações de um cliente específico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                document:
                  type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Cliente atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  document:
                    type: string
        "400":
          description: Documento inválido
        "404":
          description: Cliente não encontrado.
        "422":
          description: Parâmetros inválidos

    delete:
      summary: Delete Customer
      tags:
        - Customers
      description: Exclui um cliente específico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Cliente excluído com sucesso.
        "404":
          description: Cliente não encontrado.

  /api/projects:
    get:
      tags:
        - Projects
      summary: Get all Projects
      parameters:
        - in: query
          name: id
          schema:
            type: integer
        - in: query
          name: customer_id
          schema:
            type: integer
        - in: query
          name: installation_type_id
          schema:
            type: integer
        - in: query
          name: location
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de projetos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    location:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    customer:
                      type: object
                      nullable: true
                    installation_type:
                      type: object
                      properties:
                        id:
                          type: integer
                        description:
                          type: string
                    equipments:
                      type: array
                      items:
                        type: object
                        properties:
                          quantity:
                            type: integer
                          equipment:
                            type: object
                            properties:
                              id:
                                type: integer
                              description:
                                type: string
        "422":
          description: Parâmetros inválidos

    post:
      tags:
        - Projects
      summary: Create new Project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                installation_type_id:
                  type: integer
                location:
                  type: string
              example:
                customer_id: 1
                installation_type_id: 1
                location: "SP"
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Projeto criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  id:
                    type: integer
        "404":
          description: Tipo de instalação não encontrado
        "422":
          description: Parâmetros inválidos

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      in: header
      name: Authorization